//
// Created by vanes on 1/11/2022.
//

#ifndef MAIN_CPP_ASSETNAME_H
#define MAIN_CPP_ASSETNAME_H

enum AssetName {
    // FONTS
    DOS,

    // IMAGES
    TITLE, ROUNDED_RECT,
    BSOD,
    INTRO_BLANK, INTRO_A, INTRO_B, INTRO_C,
    FIRST_GAME, FIRST_GAME_2A, FIRST_GAME_2B, FIRST_GAME_2C, FIRST_GAME_2D, FIRST_GAME_2E, FIRST_GAME_2F,
    CHECK_IN_A, CHECK_IN_B,
    CHECK_IN_YES,
    CHECK_IN_NO_A, CHECK_IN_NO_B,
    NEXT_GAME_INTRO_A, NEXT_GAME_INTRO_B,

    GAME_2_A, GAME_2_B, GAME_2_C, GAME_2_D, GAME_2_E, GAME_2_F,
    GAME_2_G, GAME_2_H, GAME_2_I, GAME_2_J, GAME_2_K, GAME_2_L,
    GAME_2_M, GAME_2_N, GAME_2_O, GAME_2_P, GAME_2_Q, GAME_2_R,
    GAME_2_S, GAME_2_T, GAME_2_U, GAME_2_V, GAME_2_W,

    CHECK_IN_2_A, CHECK_IN_2_B, CHECK_IN_2_C, CHECK_IN_2_D,

    POEM_A, POEM_B, POEM_C, POEM_D, POEM_E, POEM_F, POEM_G, POEM_H, POEM_I, POEM_J, POEM_K, POEM_L, POEM_M, POEM_N,

    CHECK_IN_3_A, CHECK_IN_3_B, CHECK_IN_3_C, CHECK_IN_3_D, CHECK_IN_3_E, CHECK_IN_3_F, CHECK_IN_3_G, CHECK_IN_3_H,

    HEARTS_IMG, DIAMONDS_IMG, CLUBS_IMG, SPADES_IMG,

    // SOUNDS
    BUTTON_ROLLOVER,
    CLICK_CARD,
    RED_ALERT,
    TEXT_MESSAGE,
    EIGHT_BIT_WARNING,
    EIGHT_BIT_1_UP,
    SHUFFLE,
    EIGHT_BIT_COLLECT,
    EIGHT_BIT_END,
    EIGHT_BIT_SHORT_BLIP,
    EIGHT_BIT_FAIL,
    EIGHT_BIT_INCORRECT,
    EIGHT_BIT_POSITIVE,
    EIGHT_BIT_BUTTON_APPEARS,
    EIGHT_BIT_NEXT_LINE,

    LAST_ASSET
};

#endif //MAIN_CPP_ASSETNAME_H
