//
// Created by vanes on 1/11/2022.
//

#ifndef MAIN_CPP_GAMESCREENNAME_H
#define MAIN_CPP_GAMESCREENNAME_H

enum GameScreenName
{
    SPLASH_SCREEN,
    BSOD_SCREEN,
    INTRO_SCREEN_BLANK, INTRO_SCREEN_A, INTRO_SCREEN_B, INTRO_SCREEN_C, INTRO_SCREEN_C_W_BUTTON,
    PHONE_GAME_SCREEN, PHONE_GAME_SCREEN_2A, PHONE_GAME_SCREEN_2B, PHONE_GAME_SCREEN_2C, PHONE_GAME_SCREEN_2D, PHONE_GAME_SCREEN_2E, PHONE_GAME_SCREEN_2F, PHONE_GAME_SCREEN_2F_W_BUTTON,

    CHECK_IN_SCREEN_BLANK, CHECK_IN_SCREEN_A, CHECK_IN_SCREEN_B, CHECK_IN_SCREEN_B_W_1_BUTTON, CHECK_IN_SCREEN_B_W_2_BUTTONS,
    CHECK_IN_SCREEN_YES_BLANK, CHECK_IN_SCREEN_YES,
    CHECK_IN_SCREEN_NO_BLANK, CHECK_IN_SCREEN_NO_A, CHECK_IN_SCREEN_NO_B,
    NEXT_GAME_INTRO_SCREEN_BLANK, NEXT_GAME_INTRO_SCREEN_A, NEXT_GAME_INTRO_SCREEN_B, NEXT_GAME_INTRO_SCREEN_B_W_BUTTON,

    GAME_2_SCREEN_A, GAME_2_SCREEN_A_NO_BUTTON,
    GAME_2_SCREEN_B,
    GAME_2_SCREEN_C, GAME_2_SCREEN_C_BLANK,
    GAME_2_SCREEN_D, GAME_2_SCREEN_E, GAME_2_SCREEN_F,
    GAME_2_SCREEN_G, GAME_2_SCREEN_H, GAME_2_SCREEN_I,
    GAME_2_SCREEN_J, GAME_2_SCREEN_J_BLANK,
    GAME_2_SCREEN_K, GAME_2_SCREEN_L,
    GAME_2_SCREEN_M, GAME_2_SCREEN_N, GAME_2_SCREEN_O, GAME_2_SCREEN_P, GAME_2_SCREEN_Q, GAME_2_SCREEN_R,
    GAME_2_SCREEN_S, GAME_2_SCREEN_T, GAME_2_SCREEN_U, GAME_2_SCREEN_V, GAME_2_SCREEN_W,
    GAME_2_SCREEN_M_W_BUTTON, GAME_2_SCREEN_N_W_BUTTON, GAME_2_SCREEN_O_W_BUTTON, GAME_2_SCREEN_P_W_BUTTON, GAME_2_SCREEN_Q_W_BUTTON, GAME_2_SCREEN_R_W_BUTTON,
    GAME_2_SCREEN_S_W_BUTTON, GAME_2_SCREEN_T_W_BUTTON, GAME_2_SCREEN_U_W_BUTTON, GAME_2_SCREEN_V_W_BUTTON, GAME_2_SCREEN_W_W_BUTTON,

    CHECK_IN_2_SCREEN_BLANK, CHECK_IN_2_SCREEN_A, CHECK_IN_2_SCREEN_B, CHECK_IN_2_SCREEN_B_BLANK, CHECK_IN_2_SCREEN_C, CHECK_IN_2_SCREEN_D, CHECK_IN_2_SCREEN_D_W_BUTTON,

    POEM_SCREEN_A, POEM_SCREEN_B, POEM_SCREEN_C, POEM_SCREEN_D, POEM_SCREEN_E, POEM_SCREEN_F, POEM_SCREEN_G, POEM_SCREEN_H, POEM_SCREEN_I, POEM_SCREEN_J, POEM_SCREEN_K, POEM_SCREEN_L, POEM_SCREEN_M, POEM_SCREEN_N,

    CHECK_IN_3_SCREEN_BLANK, CHECK_IN_3_SCREEN_A, CHECK_IN_3_SCREEN_B, CHECK_IN_3_SCREEN_B_BLANK, CHECK_IN_3_SCREEN_C, CHECK_IN_3_SCREEN_D, CHECK_IN_3_SCREEN_D_BLANK,
    CHECK_IN_3_SCREEN_E, CHECK_IN_3_SCREEN_F, CHECK_IN_3_SCREEN_G, CHECK_IN_3_SCREEN_H, CHECK_IN_3_SCREEN_H_W_BUTTON,

    LAST_GAME_SCREEN
};
#endif //MAIN_CPP_GAMESCREENNAME_H
